### ISSUE TITLE
DXNET.Direct2D1 cant find any nuget package?

### ISSUE THREAD

**Issue by sgf** [lepoco/dxnet#6]
DXNET.Direct2D1 cant find any nuget package?

**Comment by sgf** [comment]
System.NullReferenceException
  HResult=0x80004003
  Message=Arg_NullReferenceException
  Source=DXNET.Direct2D1
  StackTrace:
   在 DXNET.Direct2D1.LocalInterop.CalliStdCallint(Void* thisObject, Void* param0, Void* param1, Int32 param2, Int32 param3, Int32 param4, Single param5, Void* param6, Void* param7, Void* methodPtr) 在 C:\Users\super\Desktop\study\Mir3L\DXNET.Direct2D1\Generated\LocalInterop.cs 中: 第 144 行


![image](https://github.com/lepoco/dxnet/assets/2557696/bda4b6a5-2cca-470e-9f4c-7369f94fc8d7)



all of LocalInterop is Empty

![image](https://github.com/lepoco/dxnet/assets/2557696/5c1b9b06-1819-4a97-8f46-6a5a312d14c4)

**Comment by erfg12** [comment]
Same, package is missing on NuGet. I had to clone this source and compile it myself.
